package com.team127.atom.mapper;

import com.team127.atom.model.Comment;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    int insert(Comment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
//    int insertSelective(Comment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    Comment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    int updateByPrimaryKeySelective(Comment row);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
//    int updateByPrimaryKeyWithBLOBs(Comment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
//    int updateByPrimaryKey(Comment row);

    List<Comment> selectCommentByUser(String userId);

    List<Comment> selectCommentByReply(String replyId);

    List<Comment> selectPopularCommentByReply(String replyId);

    int modifyComment(String commentId, String content);

    int starComment(String userId, String commentId);

    int unStarComment(String userId, String commentId);
}