package com.team127.atom.mapper;

import com.team127.atom.model.Issue;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface IssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    int insert(Issue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    int insertSelective(Issue row);

    Issue selectByPrimaryKey(String id);

    List<Issue> selectByUserId(String id);

    int deleteByPrimaryKey(String id);

    int updateByPrimaryKeySelective(Issue row);

    List<Issue> selectByStars();

    List<Issue> selectByTime();

    List<Issue> selectByContent(String content);

    int starIssue(String userId, String issueId);

    int unStarIssue(String userId, String issueId);

    int likeIssue(String userId, String issueId);

    int dislikeIssue(String userId, String issueId);

    List<Issue> selectDraft(String userId);

    int selectUserLikeIssue(String userId, String issueId);


    int selectUserStarIssue(String userId, String issueId);

    int selectUserStarReply(String user, String reply);

    int selectUserStarComment(String userId, String commentId);

    int updateDraft(String issue, String title, String content);

    int postDraft(String issue);
}