package com.team127.atom.mapper;

import com.team127.atom.model.Note;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface NoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    int insert(Note row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    int insertSelective(Note row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    Note selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    int updateByPrimaryKeySelective(Note row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    int updateByPrimaryKey(Note row);

    List<Note> selectRepoNotes(String repoId);

    List<Note> selectStarNotes(String userId);

    int starNote(String noteId, String userId);

    int checkNoteStar(String noteId, String userId);

    List<Note> searchNotes(String input);

    List<Note> recommendNotes(String userId);

    int unStarNote(String noteId, String userId);
}