package com.team127.atom.mapper;

import com.team127.atom.model.Notification;
import com.team127.atom.model.User;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */

    int insert(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    int insertSelective(User row);

    User selectUserByName(String name);
    
    int deleteById(String  id);

    User selectUserById(String id);

    int updatePassword(User user);

    int updateUser(User user);
  
    int likeUser(String id, String likeId);

    int unlikeUser(String id, String likeId);

    int isLike(String id, String likeid);

    List<User> selectLikeUser(String id);

    List<User> selectBeLikedUser(String id);

    int selectFollowerCount(String id);

    int selectLikeUserCount(String id);

    int publishNotification(String title, String content, Long time);

    List<Notification> getNotifications();

    List<User> selectRecommendUsers(String id);

}