package com.team127.atom.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import org.springframework.stereotype.Component;

@Component
@Data
@AllArgsConstructor
public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.id
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.author
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    private String author;

    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.issue
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    private String reply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.star
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    private Integer star=0;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.created_at
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.comment
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    private String content;

    private boolean isStar=false;

    private boolean isFollow=false;

    public Comment() {
        super();
    }

    public void setIsStar(boolean isStar) {
        this.isStar = isStar;
    }

    public boolean getIsStar(){
        return this.isStar;
    }

    public boolean isFollow() {
        return isFollow;
    }

    public void setFollow(boolean follow) {
        isFollow = follow;
    }
}
