package com.team127.atom.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import org.springframework.stereotype.Component;

import java.util.List;


@Data
@AllArgsConstructor
@Component
public class Reply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.id
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.author
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    private String author;

    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.issue
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    private String issue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.star
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    private Integer star=0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.created_at
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.comment
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    private String comment;

    private boolean isFollow=false;

    private List<Comment> commentList;

    private boolean isStar = false;

    public Reply() {
        super();
    }

    public void setIsStar(boolean isStar) {
        this.isStar = isStar;
    }
    public boolean getIsStar(){
        return this.isStar;
    }

    public boolean isFollow() {
        return isFollow;
    }

    public void setFollow(boolean follow) {
        isFollow = follow;
    }
}