package com.team127.atom.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import org.springframework.stereotype.Component;

@Component
@Data
@AllArgsConstructor
public class Repository {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.id
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.owner
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    private String ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.name
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.auth
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     *
     * if auth == 0 : the repository is created by authority
     * if auth == 1 : the repository is created by user and it's public
     * if auth == 2 : the repository is created by user and it's private
     */
    private Integer auth;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    public Repository() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.id
     *
     * @return the value of collection.id
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.id
     *
     * @param id the value for collection.id
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.owner
     *
     * @return the value of collection.owner
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.owner
     *
     * @param owner the value for collection.owner
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.name
     *
     * @return the value of collection.name
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.name
     *
     * @param name the value for collection.name
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.auth
     *
     * @return the value of collection.auth
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    public Integer getAuth() {
        return auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.auth
     *
     * @param auth the value for collection.auth
     *
     * @mbg.generated Sun Mar 19 16:39:56 HKT 2023
     */
    public void setAuth(Integer auth) {
        this.auth = auth;
    }
}